baseURL: "https://jiajiang.github.io" 
title: Jia Jiang
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Home
          url: /
          weight: 1
        - name: About Me
          url: aboutme/
          weight: 2
        - name: Experience
          url: experience/
          weight: 3
        - name: Research
          url: research/
          weight: 4
        - name: Publication
          url: publication/
          weight: 5
        - name: Teaching
          url: teaching/
          weight: 6

params:
    description: "This website hosts Dr. Jia Jiang's research projects, curriculum vitae, and contact information."
    author: Jia Jiang
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    #MainSections: ["papers","archive"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jia Jiang
          subtitle: "(she/her)<br><br>I’m an atmospheric modeler and postdoctoral researcher at the Massachusetts Institute of Technology (MIT), specializing in wildfire emissions, atmospheric chemistry, and air quality modeling."
          imageUrl: "JiaJiang.jpg"
          imageWidth: 200
          imageHeight: 200
          buttons:
            - name: About Me
              url: aboutme/
            - name: Experience
              url: experience/
            - name: Research
              url: research/
            - name: Publication
              url: publication/
            - name: Teaching
              url: teaching/

    socialIcons:
        - name: Email
          url: mailto:jiajiang@mit.edu   
        - name: GitHub
          url: https://github.com/jia-jiang
        - name: LinkedIn
          url: https://www.linkedin.com/in/jia-jiang/   
        - name: CV
          url: JiaJiang_CV_2025.pdf

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jia Jiang"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2