baseURL: "https://jia-jiang.github.io/" 
title: Jia Jiang
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: CV
          url: Jia_Resume.pdf
          weight: 1
        - name: Projects
          url: projects/
          weight: 2
        - name: Data
          url: data/
          weight: 3 

params:
    description: "Hi there! I'm Jia Jiang, a postdoctoral researcher at MIT Kroll Lab. I’m passionate about atmospheric chemistry—working on developing chemical mechanisms, regional air quality modeling, and environmental justice. I love finding ways to turn academic research into real-world environmental solutions."
    author: Jia Jiang
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2007"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["cv","projects","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jia Jiang
          subtitle: "Hi there! I'm Jia Jiang, a postdoctoral researcher at MIT Kroll Lab. I’m passionate about atmospheric chemistry—working on developing chemical mechanisms, regional air quality modeling, and environmental justice. I love finding ways to turn academic research into real-world environmental solutions."
          imageUrl: "photo.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: CV
              url: Jia_Resume.pdf
            - name: Projects
              url: projects/
            - name: Data
              url: data/

    socialIcons:
        - name: Email
          url: jiajiang@mit.edu
        - name: GitHub
          url: https://github.com/jia-jiang

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jia Jiang"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

